### ISSUE TITLE
UnboundLocalError: local variable 'totaldf' referenced before assignment

### ISSUE THREAD

**Issue by ChewKinWhye** [uedaLabR/nanoDoc#1]
Obtained RNA data from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124309
Data came with fastq data
Ran Tombo resquiggling
Ran format file and obtained .pq file
Ran make5mer and obtained error below

Traceback (most recent call last):
  File "./nanoDocPrep.py", line 63, in <module>
    main()
  File "./nanoDocPrep.py", line 59, in main
    cmd()
  File "/home/kinwhye/nanoDoc/src/venv3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kinwhye/nanoDoc/src/venv3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kinwhye/nanoDoc/src/venv3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kinwhye/nanoDoc/src/venv3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kinwhye/nanoDoc/src/venv3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./nanoDocPrep.py", line 30, in make5mer
    to5merpq.mkpq(path_w,ref,refraw,out)
  File "/home/kinwhye/nanoDoc/src/to5merpq.py", line 104, in mkpq
    rawdatas, cnt = refpr.getData(chr, strand, position, uplimit)
  File "/home/kinwhye/nanoDoc/src/nanoDocUtil.py", line 117, in getData
    self.checkUpdate(chr,pos,strand)
  File "/home/kinwhye/nanoDoc/src/nanoDocUtil.py", line 106, in checkUpdate
    self.pq =self.loadpq(s,chr,pos,strand)
  File "/home/kinwhye/nanoDoc/src/nanoDocUtil.py", line 90, in loadpq
return totaldf
UnboundLocalError: local variable 'totaldf' referenced before assignment

**Comment by uedaLabR** [comment]
Could you try this again with current version of the source code? Sorry for the inconvenience.
