### ISSUE TITLE
nanoDOC.py formatfile error

### ISSUE THREAD

**Issue by RyotaKurimoto** [uedaLabR/nanoDoc#13]
Dear Dr Ueda,

Thank you for this project!
I tried "nanoDOC.py formatfile", however, the following error of JSON format was occurred.
I created the following environment ; python3.8, tensorflow 2.3, cuda/10.1 and cudnn/7.6.

used code: 
python ./nanoDoc.py formatfile -i /mydir_name/single_fast5 -o /mydir_name/testIVTout -r /mydir_name/ref.fasta -t 10

The error message:
TypeError: Object of type uint32 is not JSON serializable
ValueError: Error converting column "originalsize" to bytes using encoding JSON. Original error: Object of type uint32 is not JSON serializable

Do you have any idea? Thank you very much for your notification.

Bests,

full message was follow;
Traceback (most recent call last):
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 275, in convert
    out = np.array([json.dumps(x).encode('utf8') for x in data],
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 275, in <listcomp>
    out = np.array([json.dumps(x).encode('utf8') for x in data],
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type uint32 is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mydir_name2/nanoDoc/src/h5tobinnedPq.py", line 157, in _makeParquet
    df.to_parquet(pathout)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/pandas/core/frame.py", line 2836, in to_parquet
    return to_parquet(
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/pandas/io/parquet.py", line 420, in to_parquet
    impl.write(
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/pandas/io/parquet.py", line 301, in write
    self.api.write(
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 1222, in write
    write_simple(filename, data, fmd,
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 882, in write_simple
    rg = make_row_group(f, row_group, fmd.schema,
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 701, in make_row_group
    chunk = write_column(f, coldata, column,
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 554, in write_column
    repetition_data, definition_data, encode[encoding](data, selement), 8 * b'\x00'
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 354, in encode_plain
    out = convert(data, se)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/fastparquet/writer.py", line 284, in convert
    raise ValueError('Error converting column "%s" to bytes using '
ValueError: Error converting column "originalsize" to bytes using encoding JSON. Original error: Object of type uint32 is not JSON serializable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./nanoDoc.py", line 65, in <module>
    main()
  File "./nanoDoc.py", line 61, in main
    cmd()
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mydir_name/nanoDoc/src/venv3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "./nanoDoc.py", line 34, in formatFile
    h5tobinnedPq.makeParquet(indexf,output,ref,thread)
  File "/mydir_name2/nanoDoc/src/h5tobinnedPq.py", line 132, in makeParquet
    p.map(_makeParquet, blist)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Error converting column "originalsize" to bytes using encoding JSON. Original error: Object of type uint32 is not JSON serializable

**Comment by uedaLabR** [comment]
This is version inconsistancy between numpy and fastparquet.
