### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by bhargava-morampalli** [uedaLabR/nanoDoc#8]
Hello, 

I am getting this error when trying to run the nanoDoc. Can you please let me know if this is something you have encountered before and if so - how to solve it?

```
AttributeError: 'PqReader' object has no attribute 'pq'
```
Strange thing is that I did not have this problem during the initial runs and I am getting this on a new set of data. Any suggestions to solve this are greatly appreciated.

**Comment by bhargava-morampalli** [comment]
Pasting the entire message I got here so you can take a look. Happy to provide more details if needed.
```
Total params: 38,976
Trainable params: 38,176
Non-trainable params: 800
__________________________________________________________________________________________________
/scratch/bhargava/mods-combined-comparison/k12_native/results/nanodocpreprocess/45.pq
Traceback (most recent call last):
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 65, in <module>
    main()
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 61, in main
    cmd()
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 57, in analysis
    nanoDocAnalysis.modCall(wight,param, ref, refraw,tgraw, output, chrom, chrom, start, end, strand, minreadlen)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 173, in modCall
    start, end,refpq, targetpq,minreadlen)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 61, in callPlusStrand
    chromtgt, start, end)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 74, in eachProcess
    refdatas, cntref = refpr.getData(chrom, strand, n, cnt * 2)
  File "/home/bhargavam/nanoDoc/src/nanoDocUtil.py", line 121, in getData
    self.checkUpdate(chr,pos,strand)
  File "/home/bhargavam/nanoDoc/src/nanoDocUtil.py", line 109, in checkUpdate
    if(s!= self.currentPqs or self.pq.empty):
AttributeError: 'PqReader' object has no attribute 'pq'
```

**Comment by uedaLabR** [comment]
Maybe, you start from the position with no read depth,
this would happen. 
I will try to fix this in next version,
but please designate a start position with valid depth, meanwhile.

thanks

**Comment by bhargava-morampalli** [comment]
Thanks for the help. I did as you suggested and it resolved that error. But, in the processing - about 1000 bp in, I got another error. I am pasting this here for your reference and any suggestions to resolve this. 

```
Traceback (most recent call last):
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 65, in <module>
    main()
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 61, in main
    cmd()
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bhargavam/nanoDoc/src/venv3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bhargavam/nanoDoc/src/nanoDoc.py", line 57, in analysis
    nanoDocAnalysis.modCall(wight,param, ref, refraw,tgraw, output, chrom, chrom, start, end, strand, minreadlen)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 173, in modCall
    start, end,refpq, targetpq,minreadlen)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 61, in callPlusStrand
    chromtgt, start, end)
  File "/home/bhargavam/nanoDoc/src/nanoDocAnalysis.py", line 74, in eachProcess
    refdatas, cntref = refpr.getData(chrom, strand, n, cnt * 2)
  File "/home/bhargavam/nanoDoc/src/nanoDocUtil.py", line 121, in getData
    self.checkUpdate(chr,pos,strand)
  File "/home/bhargavam/nanoDoc/src/nanoDocUtil.py", line 110, in checkUpdate
    self.pq =self.loadpq(s,chr,pos,strand)
  File "/home/bhargavam/nanoDoc/src/nanoDocUtil.py", line 94, in loadpq
    return totaldf
UnboundLocalError: local variable 'totaldf' referenced before assignment
```

**Comment by bhargava-morampalli** [comment]
More info to add here - although the solution for the attribute error (starting at a position with valid depth) worked on a test file, I am getting this error even when making sure that I start with a position with non-zero depth.

**Comment by uedaLabR** [comment]
I fix the code. Pls let me know if you have further problem.
Also I changed scoring scheme a bit.

**Comment by bhargava-morampalli** [comment]
Thanks for doing this quickly. I tried it out and it worked well. 
I have a question - I have been trying nanoDoc with my direct RNA sequencing data in E. coli. I get the expected peaks but they are always off by a few nucleotides to the right. 
Also, the scoring levels are way lower than the scores that the paper shows with E. coli
I have a fairly decent coverage for ribosomal RNAs (anywhere between 1000-5000x) and was wondering what the problem might be. Any insights are helpful. Thanks.
